# Generated by Django 4.0.3 on 2024-03-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskToPeerApp', '0005_room_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_data', to='AskToPeerApp.room')),
            ],
        ),
    ]
